name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX
publish_to: 'none'

version: 1.0.0+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  flutter_cart: ^0.0.9
  get_storage: ^2.1.1
  flutter_secure_storage: ^8.1.0
  flutter_login: ^5.0.0
  webview_flutter: ^4.7.0
  flutter_stripe: ^10.1.1
  onesignal_flutter: ^5.2.0
  sentry_flutter: ^9.20.0
  package_info_plus: ^10.1.0
  uuid: ^4.5.3
  http: ^1.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  sentry_dart_plugin: ^3.3.0

sentry:
  upload_debug_symbols: true
  upload_source_maps: false
  upload_sources: true
  wait_for_processing: true
  log_level: error
  commits: auto
  ignore_missing: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_logo_square.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_logo_square.png"

flutter_native_splash:
      color: "#000000"
      image: assets/images/app_logo_splash.png
      android_12:
        color: "#000000"
        image: assets/images/app_logo_splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
